### PR TITLE
Update dpdk

### LINKED ISSUE #48: Should use newer version of DPDK
DPDK LTS releases 21.11+ contain breaking API changes that prevent compilation. At this point, 21.08 is ~3 years old, and DPDK typically stops maintaining LTS's after 3 years.

### PR DESCRIPTION
**Pull request by HKalbasi**
This PR adds support for building against DPDK 23.11 without losing support for DPDK 20.11 (the old CI) and 21.08 (the old advertised version). And the infrastructure for adding more versions is here so I can add more if needed.

This PR:
- Makes CI check for both 20.11 and 23.11
- Updates the README to mention support for DPDK 23.11
- Adds some CFG flags in the build script to be able to build the code with multiple DPDK versions

fix #48

### CODE REVIEW

**Comment by HKalbasi** [comment]
@thearossman This is ready for review.

File: INSTALL.md [hunk 1]
```diff
@@ -24,7 +24,7 @@ sudo apt install build-essential meson pkg-config libnuma-dev python3-pyelftools
 ```
 
 ## Building and Installing DPDK
-Retina currently requires [**DPDK 21.08**](https://core.dpdk.org/download/). The latest LTS release (21.11) contains breaking API changes while 20.11 LTS has a bug that causes inaccurate packet drop metrics on some NICs.
+Retina currently requires [**DPDK 20.11 or 21.08 or 23.11**](https://core.dpdk.org/download/). Note that 20.11 LTS has a bug that causes inaccurate packet drop metrics on some NICs.
```
Comment (thearossman) [inline INSTALL.md:27]: Good catch. Do you know which NICs?

File: INSTALL.md [hunk 2]
```diff
@@ -63,15 +63,16 @@ sudo /etc/init.d/openibd restart
 This may update the firmware on your NIC, a reboot should complete the update if necessary.
 
 ### Install DPDK from source
-We recommend a local DPDK install from source. Download version 21.08 from the [DPDK downloads page](http://core.dpdk.org/download/):
+We recommend a local DPDK install from source. Download version 23.11 from the [DPDK downloads page](http://core.dpdk.org/download/):
```
Comment (thearossman) [inline INSTALL.md:66]: version 23.11 (or desired version)

File: core/src/dpdk/mod.rs [hunk 3]
```diff
@@ -9,6 +9,84 @@ include!(concat!(env!("OUT_DIR"), "/dpdk.rs"));
...
+        self.version_ihl = version_ihl;
+    }
+
+    #[cfg(dpdk_ge_2311)]
+    pub fn set_version_ihl(&mut self, version_ihl: u8) {
+        self.__bindgen_anon_1.version_ihl = version_ihl;
+    }
+}
+
+// Bindgen doesn't support complex macros, so we need these
```
Comment (thearossman) [inline core/src/dpdk/mod.rs:36]: I don't think this is true. See 

https://github.com/stanford-esrg/retina/blob/6ea7f1dfab8087fa29954765c8ca3a30674be5be/core/src/port/mod.rs#L298

File: core/src/port/mod.rs [hunk 4]
```diff
@@ -19,11 +19,12 @@ use std::ptr;
 
 use anyhow::{bail, Result};
 
-const RSS_KEY_LEN: usize = 40;
+const RSS_KEY_LEN: usize = 52;
```
Comment (thearossman) [inline core/src/port/mod.rs:22]: Why this change? Will this impact anything in RSS (e.g., sink core, load-balancing key)?

File: INSTALL.md [hunk 5]
```diff
@@ -63,15 +63,16 @@ sudo /etc/init.d/openibd restart
...
-tar xJf dpdk-21.08.tar.xz
+wget http://fast.dpdk.org/rel/dpdk-23.11.tar.xz
+tar xJf dpdk-23.11.tar.xz
 ```
 
 Set environment variables:
 ```sh
-export DPDK_PATH=/path/to/dpdk/dpdk-21.08
+export DPDK_PATH=/path/to/dpdk/dpdk-23.11
+export DPDK_VERSION=23.11
```
Comment (thearossman) [inline INSTALL.md:75]: Can you clarify how one would change the DPDK version? It's just by setting the environment variable, right? (I.e., not a feature flag in Cargo.toml?)

**Comment by thearossman** [comment]
Thank you! Hoping @tbarbette or @thegwan could take a quick look at some point, as I think they are more well-versed in DPDK details and this build pipeline than I am.

File: core/src/port/mod.rs (hunk 4 above)
Comment (thearossman) [reply core/src/port/mod.rs:22]: Also -- this needs to be wrapped in a feature flag. Not sure if it's a result of my NIC or DPDK version (I ran this on 21.08), but my runtime requires RSS key size 40.

File: core/src/dpdk/mod.rs (hunk 3 above)
Comment (HKalbasi) [reply core/src/dpdk/mod.rs:36]: The problem is that in DPDK 23.11 these constants are defined with a function macro `RTE_BIT64(x)` and bindgen doesn't support function macros. In old DPDK these were ok.

File: core/src/port/mod.rs (hunk 4 above)
Comment (HKalbasi) [reply core/src/port/mod.rs:22]: Ah, I forgot to add gate for these. In 23.11 this length is 52 and in 20.11 is 40. We should probably have some smoke test in CI to detect if a simple retina example can be executed successfully.

File: INSTALL.md (hunk 1 above)
Comment (HKalbasi) [reply INSTALL.md:27]: I don't know, I just kept the previous message about this version.

File: INSTALL.md (hunk 5 above)
Comment (thearossman) [reply INSTALL.md:75]: I don't think so; just wanted to clarify (that feature flag is set in the build.rs based on the env variable).

File: core/src/dpdk/mod.rs (hunk 3 above)
Comment (thearossman) [reply core/src/dpdk/mod.rs:36]: Got it - sorry for missing that. Ideally the code wouldn't redefine the constants from scratch so that we can better ensure consistency with the original DPDK. Though I think this could be put into an issue to be addressed in a later commit.

I did a quick search through GitHub and couldn't find other projects that have needed to do this with recent DPDK versions. 

I'm wondering if there's a clean way to force preprocessing to expand the function macros 
- Maybe there's something in build.rs: https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html 
- Instead of these defs in a .rs file, I assume putting them in a C file would allow defining these consts with direct reference to the DPDK function macros. (E.g., `define RTE_ETH_RSS_IPV4_ RTE_ETH_RSS_IPV4` --> bindgen can expose these to the rest of the crate.) 

What do you think?

File: core/src/port/mod.rs (hunk 4 above)
Comment (thegwan) [reply core/src/port/mod.rs:32]: Did you check if this new RSS key still properly performs symmetric RSS? I'm not entirely sure if it should be zero-padded or if continuing the byte pattern is correct.

**Review by thegwan — APPROVED** [review]
Code changes LGTM, but I'll leave it to @thearossman and @HKalbasi to verify correct behavior since I don't have access to a DPDK environment right now. Something to verify would be that the NIC counters still work properly. Last time I checked the 20.11 release had a bug that will affect the perceived throughput and I don't know if this has been fixed in later releases.

File: core/src/port/mod.rs (hunk 4 above)
Comment (tbarbette) [reply core/src/port/mod.rs:32]: The size does not depend on the version but on the type of NIC, this patch will break some NICs, and enable some others. I remember I carried my diff for the SIGCOMM paper. The right length should be queried with rte_eth_dev... Something:)

Comment (HKalbasi) [reply core/src/port/mod.rs:32]: Are you sure? I was able to run retina with dpdk 20.08 on my NICs (Intel 710 and 810) with length 40 but it required 52 with dpdk 23.11 and the same NICs.

Comment (tbarbette) [reply core/src/port/mod.rs:32]: In fstack they have the 40 by default, but if the NIC requires 52 they use the 52 one. The symmetrical can be shorten of course, it's just a matter of setting the right length. https://github.com/F-Stack/f-stack/blob/8c6094901e4a035bac8324a5cc590ea9b6a7eb35/lib/ff_dpdk_if.c#L663

File: core/src/dpdk/mod.rs (hunk 3 above)
Comment (HKalbasi) [reply core/src/dpdk/mod.rs]: I found out that new bindgen has a `clang_macro_fallback` which solves this problem. So I updated the bindgen and removed those manual copies.

File: core/build.rs [hunk 6]
```diff
@@ -113,6 +137,7 @@ fn main() {
     let mut builder = cc::Build::new();
     builder.opt_level(3);
     builder.pic(true);
+    builder.flag("-mssse3");
```
Comment (thearossman) [inline core/build.rs:140]: Is this added due to the DPDK version change? (Shouldn't native arch be fine?)

Comment (HKalbasi) [reply core/build.rs:140]: No, I just needed this to be able to build retina on NixOS. I guess `-march=native` doesn't work on NixOS for reproducability reasons. Its harmless on other OSes.

Comment (tbarbette) [reply core/build.rs:140]: It will break on ARM :)

Comment (HKalbasi) [reply core/build.rs]: I removed the line. I can add it in my local tree when bulding for NixOS. Btw, it would be nice to have an ARM CI.

Comment (thearossman) [reply core/build.rs]: Agree! there's a bug open on this, but we haven't yet been able to prioritize it.

**Comment by thearossman** [comment]
Okay! I just tested this PR on both ARM and x86 (ARM only offline mode), with both DPDK 21.08 and 23.11 LTS. 

@HKalbasi I got this error when trying to build with 23.11 in on x86: 

```
error[E0432]: unresolved import `RTE_ETH_RSS_IP`
  --> core/src/dpdk/mod.rs:43:9
   |
43 | pub use RTE_ETH_RSS_IP as ETH_RSS_IP;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no external crate `RTE_ETH_RSS_IP`

error[E0432]: unresolved import `RTE_ETH_RSS_TCP`
  --> core/src/dpdk/mod.rs:45:9
   |
45 | pub use RTE_ETH_RSS_TCP as ETH_RSS_TCP;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no external crate `RTE_ETH_RSS_TCP`

error[E0432]: unresolved import `RTE_ETH_RSS_UDP`
  --> core/src/dpdk/mod.rs:47:9
   |
47 | pub use RTE_ETH_RSS_UDP as ETH_RSS_UDP;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no external crate `RTE_ETH_RSS_UDP`
``` 

For DPDK, I used `wget http://fast.dpdk.org/rel/dpdk-23.11.tar.xz`. We're on Ubuntu 20.04.6. 

Is there anything else I need to configure to ensure the `clang_macro_fallback` works?

**Comment by HKalbasi** [comment]
Can you try again? I remember it failed spuriously one time. It builds on my machine and CI, both are x86.

**Comment by thearossman** [comment]
> Can you try again? I remember it failed spuriously one time. It builds on my machine and CI, both are x86.

Did it fail with this same error? I've tried it a few times. Is there anything you did to make it work the second time around? 

I agree, it doesn't make sense that it would fail on our machines with this.

**Comment by HKalbasi** [comment]
It was similar if I recall correctly, but it was just one time and I didn't see it later.

I'm on ubuntu 22.04 and CI is on 24.04, so maybe it is clang/llvm version? What is your OS on the ARM machine?

**Comment by thearossman** [comment]
> It was similar if I recall correctly, but it was just one time and I didn't see it later.
> 
> I'm on ubuntu 22.04 and CI is on 24.04, so maybe it is clang/llvm version? What is your OS on the ARM machine?

Oh, you're completely right. Looks like clang_macro_fallback requires clang 13+ (I think? not entirely sure what the minimum version would be). We had clang 10. 

I did a full upgrade. Compiling and running seem to work. Stats and outputs seem to match what we had with the older DPDK version. 

I can make two small doc edits to this PR: 
- To the INSTALL.md to note the clang requirement. 
- This note in a comment, though it shouldn't impact the DPDK values: https://github.com/rust-lang/rust-bindgen/issues/2944

Otherwise, I feel great about merging this on Monday unless Tom/Gerry have concerns. 

Thank you so much for this.

File: core/src/port/mod.rs [hunk 7]
```diff
@@ -292,15 +298,24 @@ impl Port {
         // turn on RSS
         if dev_info.flow_type_rss_offloads != 0 {
             port_conf.rxmode.mq_mode = dpdk::rte_eth_rx_mq_mode_ETH_MQ_RX_RSS;
-            port_conf.rx_adv_conf.rss_conf.rss_key = SYMMETRIC_RSS_KEY.as_ptr() as *mut u8;
-            port_conf.rx_adv_conf.rss_conf.rss_key_len = RSS_KEY_LEN as u8;
+            let symmetric_rss_key = if dev_info.hash_key_size == 52 {
+                SYMMETRIC_RSS_KEY_52.as_slice()
```
Comment (tbarbette) [inline core/src/port/mod.rs:302]: Is it due to a Rust memory safeness thing that you can't use 40 bytes out of the 52 key length? Else, you can use simply the 52 one, just consider a length of 40 out of the 52 as they're the same.

**Comment by tbarbette** [comment]
@EngAlessandroMaggi maybe you can try this PR to see if nothing breaks on your system?

File: core/src/port/mod.rs (hunk 7 above)
Comment (HKalbasi) [reply core/src/port/mod.rs]: There was no reason, I unified the keys.

**Comment by EngAlessandroMaggi** [comment]
> @EngAlessandroMaggi maybe you can try this PR to see if nothing breaks on your system?

**Compiling and running seems to be working fine.**

Using the following versions: 
- DPDK 23.11.2
- cargo 1.85.0-nightly 
- lang version 14.0.0 
- bindgen 0.71.1 
- meson 0.56.0
